target 'DRYSlidingMenu', :exclusive => true do
  pod "DRYSlidingMenu", :path => "../"
  pod "Masonry"
end

target 'Tests', :exclusive => true do
  pod "DRYSlidingMenu", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
