target 'DRYSlidingMenu', :exclusive => true do
  pod "DRYSlidingMenu", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DRYSlidingMenu", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase', '~> 1.6'
  pod 'Expecta+Snapshots'
end
