# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

before_install:
    - cd Example

script:
- xctool test -workspace DRYSlidingMenu.xcworkspace -scheme DRYSlidingMenu -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
